# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "About"
pageRef = "about"
weight = 1

[[main]]
name = "Blog"
pageRef = "tags"
weight = 2

[[main]]
name = "Publications"
pageRef = "publications"
weight = 3

[[main]]
name = "Press"
pageRef = "press"
weight = 4

[[main]]
name = "Investments"
pageRef = "investments"
weight = 5

[[main]]
name = "Sustainable Computing"
pageRef = "sustainable-computing"
weight = 6

[[main]]
name = "Reading"
pageRef = "reading"
weight = 7

[[main]]
name = "Contact"
pageRef = "contact"
weight = 9

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
